[bumpver]
current_version = "9.5.9"
version_pattern = "MAJOR.MINOR.PATCH[.INC0]"
commit_message = "Bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[bumpver.file_patterns]
"bumpver.toml" = ['^current_version = "{version}"$']
"chez-scheme-hs.cabal" = [
  '^version:            {pep440_version}',
  '^copyright:          Â© 2022-YYYY Wen Kokke$',
]
